[[constraint]]
  name = "github.com/envoyproxy/go-control-plane"
  version = "0.4.0"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.1.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.11.1"

[prune]
  go-tests = true
  unused-packages = true
